apiVersion: apps/v1
kind: Deployment
metadata:
  name: east-shopping-deployment
  labels:
    app: east-shopping
spec:
  replicas: 4
  selector:
    matchLabels:
      app: east-shopping
  template:
    metadata:
      labels:
        app: east-shopping
    spec:
      containers:
      - name: east-shopping-container
        image: deployment/east-shopping-js:1.0
        ports:
        - containerPort: 5000
        env:
          -name: MONGO_URL
          value: mongodb://mongo:27017/east-shopping
        imagePulllPolicy: Always